# Generated by Django 3.0.2 on 2020-01-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='photo',
            field=models.ImageField(upload_to='nails_photo'),
        ),
    ]
