# Generated by Django 3.0.2 on 2020-01-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_auto_20200115_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='works',
            name='date',
        ),
        migrations.RemoveField(
            model_name='works',
            name='title',
        ),
    ]
